Sunbird-inQuiry/data-pipeline

publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/domain/Event.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/domain/Models.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/function/PublishEventRouter.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/function/QuestionRePublishFunction.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/function/QuestionSetRePublishFunction.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/helpers/LiveObjectReader.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/helpers/QuestionPublisher.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/helpers/QuestionSetPublisher.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/task/QuestionSetRePublishConfig.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/task/QuestionSetRePublishStreamTask.scala
publish-pipeline/questionset-republish/src/test/scala/org/sunbird/job/republish/helpers/spec/QuestionPublisherSpec.scala
publish-pipeline/questionset-republish/src/test/scala/org/sunbird/job/republish/helpers/spec/QuestionSetPublisherSpec.scala

Issue #IQ-149 fix: package renamed

---

jobs-core/src/main/scala/org/sunbird/job/util/CloudStorageUtil.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #IQ-45 feat: CSP changes

---

jobs-core/src/main/scala/org/sunbird/job/util/CloudStorageUtil.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #IQ-25 fix: updated code for storage endpoint

---

jobs-core/src/main/scala/org/sunbird/job/util/CloudStorageUtil.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #IQ-25 fix: updated code for csp

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml

Issue #IQ-25 fix: deleted unwanted config

---

kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #IQ-193 feat: updated cloud variables

---

kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #IQ-193 feat: updated variables

---

jobs-core/src/main/scala/org/sunbird/job/util/CSPMetaUtil.scala
kubernetes/helm_charts/datapipeline_jobs/values.j2
publish-pipeline/async-questionset-publish/src/main/resources/async-questionset-publish.conf
publish-pipeline/questionset-republish/src/main/resources/questionset-republish.conf

Issue #IQ-193 feat: added variables for relative path

---

publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/function/QuestionRePublishFunction.scala

Issue #IQ-194 fix: added fix for invalid objects

---

ansible/inventory/env/group_vars/all.yml

Issue #IQ-149 fix: updated variable

---

.circleci/config.yml
jobs-core/src/main/scala/org/sunbird/job/util/Neo4JUtil.scala
publish-pipeline/publish-core/src/main/scala/org/sunbird/job/publish/helpers/ObjectUpdater.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectBundleSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectPdfGeneratorSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectReaderTestSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectUpdaterSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ThumbnailGeneratorSpec.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/function/QuestionRePublishFunction.scala
publish-pipeline/questionset-republish/src/main/scala/org/sunbird/job/questionset/republish/function/QuestionSetRePublishFunction.scala
publish-pipeline/questionset-republish/src/test/scala/org/sunbird/job/republish/helpers/spec/QuestionPublisherSpec.scala
publish-pipeline/questionset-republish/src/test/scala/org/sunbird/job/republish/helpers/spec/QuestionSetPublisherSpec.scala

Issue #IQ-31 feat: updated circle ci script & test cases

---

jobs-distribution/Dockerfile

Issue #000 feat: S3 presto dependency added

---

.circleci/config.yml

update circle ci config

---

publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/helpers/QuestionPublisher.scala

Issue #IQ-478 fix: code changes for answer validation

---

jobs-core/pom.xml
jobs-distribution/Dockerfile
kubernetes/helm_charts/datapipeline_jobs/templates/flink_job_deployment.yaml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #ED-2072 feat: changes done for oci

---

publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/helpers/QuestionSetPublisher.scala

Issue #IQ-558 fix: code changes for json props

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #IQ-591 fix: removed old variables

---

ansible/inventory/env/group_vars/all.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2

Issue #IQ-591 fix: updated variable values

---

scripts/jenkins-jobs/ArtifactUpload/KnowledgePlatform/InquiryFlinkJob/config.xml
scripts/jenkins-jobs/Build/KnowledgePlatform/InquiryFlinkJob/config.xml
scripts/jenkins-jobs/Deploy/KnowledgePlatform/InquiryFlinkJob/config.xml

Issue IQ-645 feat: added jenkins job scripts

---

ansible/inquiry_kafka_setup.yml
ansible/inventory/env/group_vars/all.yml
ansible/roles/inquiry-setup-kafka/defaults/main.yml
ansible/roles/inquiry-setup-kafka/tasks/main.yml
kubernetes/pipelines/deploy/setup-kafka/JenkinsFile
scripts/jenkins-jobs/Deploy/KnowledgePlatform/InquiryKafkaSetup/config.xml

Issue #IQ-654 feat: added ansible script for kafka setup

---

ansible/inquiry_kafka_setup.yml
ansible/inventory/env/group_vars/all.yml
ansible/roles/inquiry-setup-kafka/defaults/main.yml
ansible/roles/inquiry-setup-kafka/tasks/main.yml
kubernetes/pipelines/deploy/setup-kafka/JenkinsFile
scripts/jenkins-jobs/Deploy/KnowledgePlatform/InquiryKafkaSetup/config.xml

Issue #IQ-564 fix: added kafka topic for quml migration

---

quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/helpers/QuestionMigrator.scala
quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/helpers/QuestionSetMigrator.scala

Issue #IQ-664 fix: added compatibilityLevel for quml migration

---

quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/function/QuestionMigrationFunction.scala
quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/function/QuestionSetMigrationFunction.scala
quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/helpers/QuestionMigrator.scala
quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/helpers/QuestionSetMigrator.scala
quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/helpers/QumlMigrator.scala

Issue #IQ-669 fix: fix for migration error message

---

quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/helpers/QuestionMigrator.scala
quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/helpers/QuestionSetMigrator.scala

Issue #IQ-669 fix: updated exception message handling

---

quml-migrator/src/main/scala/org/sunbird/job/quml/migrator/domain/Event.scala

Issue #IQ-669 fix: fix for event validation

---

jobs-core/src/test/scala/org/sunbird/spec/FileUtilsSpec.scala
jobs-core/src/test/scala/org/sunbird/spec/HTTPUtilSpec.scala
kubernetes/ansible/roles/flink-jobs-deploy/defaults/main.yml
kubernetes/helm_charts/datapipeline_jobs/values.j2
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/EcarGeneratorSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectBundleSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectEnrichmentSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectPdfGeneratorSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ObjectUpdaterSpec.scala
publish-pipeline/publish-core/src/test/scala/org/sunbird/job/publish/spec/ThumbnailGeneratorSpec.scala
user-pii-data-updater/src/main/resources/user-pii-data-updater.conf
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/domain/Event.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/domain/Models.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/OwnershipTransferFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiEventRouter.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/helpers/Neo4jDataProcessor.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/helpers/UserPiiUpdater.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/task/UserPiiUpdaterConfig.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/task/UserPiiUpdaterStreamTask.scala
user-pii-data-updater/src/test/resources/test.conf
user-pii-data-updater/src/test/scala/org/sunbird/job/user/pii/updater/task/UserPiiUpdaterConfigSpec.scala

Issue #IQ-656 feat: code changes for ownership transfer

---

jobs-core/src/main/scala/org/sunbird/job/util/LoggerUtil.scala
publish-pipeline/async-questionset-publish/src/main/resources/log4j.properties
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/PublishEventRouter.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionSetPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/domain/Event.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/domain/Models.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/task/QuestionSetPublishConfig.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/domain/Event.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/domain/Models.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/OwnershipTransferFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiEventRouter.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiUpdateFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/helpers/NotificationProcessor.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/helpers/UserPiiUpdater.scala
user-pii-data-updater/src/test/scala/org/sunbird/job/user/pii/updater/helpers/NotificationProcessorSpec.scala

Issue #IQ-404 feat: code changes for entry and exit logging

---

publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/PublishEventRouter.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionSetPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/util/QuestionPublishUtil.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/OwnershipTransferFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiEventRouter.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiUpdateFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/helpers/UserPiiUpdater.scala

Issue #IQ-751 feat: added feature id in logging

---

publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/PublishEventRouter.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionSetPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/util/QuestionPublishUtil.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/OwnershipTransferFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiEventRouter.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiUpdateFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/helpers/UserPiiUpdater.scala

Issue #IQ-751 fix: updated loggers

---

publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/helpers/QuestionPublisher.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/helpers/QuestionSetPublisher.scala

Issue #IQ-379 fix: added code for prevStatus

---

publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/PublishEventRouter.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/function/QuestionSetPublishFunction.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/domain/Event.scala
publish-pipeline/async-questionset-publish/src/main/scala/org/sunbird/job/questionset/publish/util/QuestionPublishUtil.scala
publish-pipeline/async-questionset-publish/src/test/scala/org/sunbird/job/publish/util/spec/QuestionPublishUtilSpec.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/domain/Event.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/OwnershipTransferFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiEventRouter.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/function/UserPiiUpdateFunction.scala
user-pii-data-updater/src/main/scala/org/sunbird/job/user/pii/updater/helpers/UserPiiUpdater.scala

Issue #IQ-793 fix: added code for feature name

---

ansible/roles/inquiry-setup-kafka/defaults/main.yml

Issue #IQ-656 fix: added kafka topic for ownership transfer
